# Site settings
title: Jean-Bertrand Uwilingiyimana
email: jbu@jean-bertrand.com
url: https://jean-bertrand.github.io
description: "Socially conscious dreamer and digital experience designer currently designing @WholeFoods"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6c7a89 #80B3FF
  secondary: ea863d #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jean-Bertrand Uwilingiyimana
  location: Location
  social: Connect with Me
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/juwiling
  - title: linkedin
    url: https://www.linkedin.com/in/jeanuwilingiyimana
  - title: github
    url: https://github.com/jean-bertrand
  - title: instagram
    url: https://instagram.com/juwiling
    

# Postal address (add as many lines as necessary)
address:
  - line: Austin, TX

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
paginate: 10
pygments: rouge
